import { lightTheme } from '../templates/themes';
import Providers from '../ui/components/Provider';
import './global.css';

import { ThemeProvider } from '@mui/material';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>j4db</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <ThemeProvider theme={lightTheme}>
        <body className=" bg-[#FDFDFD] w-[100vw] h-[100vh]">
          <Providers>{children}</Providers>
        </body>
      </ThemeProvider>
    </html>
  );
}
